### ISSUE TITLE
[Request] Mob spawning controls for advanced crying obsidian

### ISSUE THREAD

**Issue by Saereth** [ErrorCraftLP/Crying-Obsidian#13]
Allowing us to set a respawn delay timer for NPCs on the advanced crying obsidian or a blacklist/whitelist would be very useful.

One feature the players love is the ability to have their mounts/pets respawn there if they die, an unfortunate side effect is mods like soul shards and deep mob learning that normally would require you to hunt lots of mobs can be cheesed by simply spam respawning a blaze or whatever on the advanced crying obsidian. Being able to whitelist mounts or blacklist those mobs or just being able to set a long respawn timer would all be welcome additions, whatever is easiest for you. 

Thanks for the consideration. Also if you accept PRs I wouldnt mind writing this functionality up and doing a PR if you prefer.

**Comment by ErrorCraftLP** [comment]
I'm sorry that it took me so long to reply, but I added a re-spawn whitelist in the new v1.2.0 update.

**Comment by Saereth** [comment]
oh great, thanks!
